name: Main CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-export:
    name: Build and export Docker
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Context for Buildx
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          endpoint: builders

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/darkness4/container-tools
          tags: |
            latest
            v1
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          platforms: linux/amd64
          load: true
          push: false
          tags: sbom-test
          labels: ${{ steps.docker_meta.outputs.labels }}
          annotations: ${{ steps.docker_meta.outputs.annotations }}

      - name: Compute SBOM
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $PWD:/work \
            -w /work \
            ghcr.io/anchore/syft:latest \
            --output github-json=sbom.new.json \
            sbom-test

      - name: Restore Previous SBOM from Cache
        id: cache-sbom
        uses: actions/cache/restore@v4
        with:
          path: sbom.json
          key: sbom
          restore-keys: sbom-

      - name: Compare SBOMs
        id: compare
        run: |
          if diff -q <(jq -S '[.manifests[].resolved | keys[]] | sort' sbom.json) <(jq -S '[.manifests[].resolved | keys[]] | sort' sbom.new.json); then
            echo "sbom=unchanged" >> $GITHUB_OUTPUT
          else
            echo "Changes detected:"
            diff -Nau <(jq -S '[.manifests[].resolved | keys[]] | sort' sbom.json) \
                      <(jq -S '[.manifests[].resolved | keys[]] | sort' sbom.new.json) || true
            echo "sbom=changed" >> $GITHUB_OUTPUT
          fi

      - name: Build and export
        if: steps.compare.outputs.sbom == 'changed'
        uses: docker/build-push-action@v6
        id: build-and-push
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          attests: type=sbom
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          annotations: ${{ steps.docker_meta.outputs.annotations }}

      - name: Replace old SBOM
        run: |
          mv sbom.new.json sbom.json

      - name: Save SBOM to Cache
        if: steps.compare.outputs.sbom == 'changed'
        uses: actions/cache/save@v4
        with:
          path: sbom.json
          key: sbom-${{ hashFiles('sbom.json') }}

      - name: Sign the images with GitHub OIDC Token
        if: steps.compare.outputs.sbom == 'changed'
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ${{ steps.docker_meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
